spring:
    profiles:
        active:
            - dog
            - EN
            - qa
guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
spring:
    profiles: prod
guru:
    username: YmlUserName.PROD
    password: YmlPassword.PROD
    jdbcurl: YmlUrl.PROD